# action.yml
name: 'Action:  run Asciidoctor'
description: 'Generates HTML'

inputs:
  output:
    description: "Full path of artifact (tarball) to produce."
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.output }}

