name: Build asciidocs (revised)

on:
  push:
    branches:
    - main

jobs:
  buildhtml:
    runs-on: ubuntu-latest
    name: Generate HTML from asciidoc
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
#      - name: Build HTML from Asciidoc
#        uses: ./action
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          pdf_build: false

