name: "Workflow:  Build asciidocs"

on:
  push:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
#permissions:
#  contents: read
#  pages: write
#  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  buildhtmljob:
    runs-on: ubuntu-latest
    name: "Job:  Generate HTML from Asciidoc"
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: "Step:  Checkout"
        uses: actions/checkout@v4
      - name: "Step:  Build HTML from Asciidoc"
        uses: ./action
#      - name: "Step:  Equinor build"
#        id: adocbuild
#        uses: equinor/asciidoctor-action@main
#        with:
#          entry_point: test
#          docs_folder: ./docs

