name: "Workflow:  Build asciidocs"

on:
  push:
    branches:
    - main

jobs:
  buildhtmljob:
    runs-on: ubuntu-latest
    name: "Job:  Generate HTML from Asciidoc"
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: "Step:  Checkout"
        uses: actions/checkout@v4
#      - name: "Step:  Build HTML from Asciidoc"
#        uses: ./action
      - name: "Step:  Equinor build"
        id: adocbuild
        uses: equinor/asciidoctor-action@main
        with:
          entry_point: test
          docs_folder: ./docs
